### ISSUE TITLE
unwarp_parameter_maps and unwarp_parameter_maps

### ISSUE THREAD

**Issue by lxy2017** [facebookresearch/BioSkin#2]
Hi, thank you for your research. I'm a little confused about the purpose of these two functions， unwarp_parameter_maps and unwarp_parameter_maps， in train.py    parameters_train, parameters_test = remap_parameters_tensors(parameters_train, parameters_test)  , Skin data is processed by the unwarp_parameter_maps function， I'm not sure what that means.   In save_parameter_maps,  parameters = warp_parameter_maps(parameters)

**Comment by carlosaliaga** [comment]
Hi, 
To generate samples that uniformly cover the range of skin tones, melanin and hemoglobin are selected cubicly and quarticly respectively, to better adjust to their non-linear effect on reflectance. Also, the epidermal thickness has a range of 10 to 350 microns. For training, we take those parameters, sampled non-linearly, and map them into a linear, normalized space of 0 to 1 for all the skin properties. At inference time (and also for the supervised skin properties loss during training), we need to do the inverse operation to recover the original values of the parameters and not their normalized form. Hope this answers your question.

**Comment by lxy2017** [comment]
Thanks!
